### ISSUE TITLE
EM-means for the WGEE models

### ISSUE THREAD

**Issue by ghost** [cran/wgeesel#1]
Dear Authors, 
Would it be possible to add the support for the EM-means? It works with GEE, but not with WGEE yet. This would enable to use the advantages of GEE on MAR data.

Please find crosslinked topic:
https://github.com/rvlenth/emmeans/issues/165

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!
